service: myserverlessproject

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile:  serverlessUser

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: myserverlessprojectuploadtest-1231234
      localDir: myfolder

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUploadTest:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myserverlessprojectuploadtest-1231234
